# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache the dependencies for building
      - restore_cache:
          keys:
          - v1-dependencies-build-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-build-{{ checksum "yarn.lock" }}
      - run:
          name: Build Keystone Plugin Bundles
          command: |
            CLIENT_SOCKETIO_HOST=keystone-plugin.twreporter.org
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              CLIENT_SOCKETIO_HOST=staging-keystone-plugin.twreporter.org
            fi
            CLIENT_SOCKETIO_HOST=$CLIENT_SOCKETIO_HOST CLIENT_SOCKETIO_PROTOCOL=https CLIENT_SOCKETIO_PORT=443 make build-keystone-plugin

      - run: rm -rf node_modules

      # Download and cache the dependencies for running
      - restore_cache:
          keys:
            - v1-dependencies-runtime-{{ checksum "yarn.lock" }}
      - run: yarn install --production
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-runtime-{{ checksum "yarn.lock" }}

      - run:
          name: Save pkg version to a file
          command: node ./.circleci/scripts/read-changelog.js > .pkg-version

      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*
  push:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - setup_remote_docker

      - attach_workspace:
          at: .

      - run:
          name: Build and push Docker image
          command: |
            # GOOGLE_AUTH is defined in Environment Variables of circleci project
            # GOOGLE_AUTH is used to grant CircleCI vm to have the permission to access GCP
            echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json

            PKG_VER="$(cat .pkg-version)-$CIRCLE_BUILD_NUM"

            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              PKG_VER="$(cat .pkg-version)"
            fi

            echo "PKG_VER: ${PKG_VER}"

            # gcs key file
            echo ${GCS_KEY_FILE} | base64 -i --decode > gcskeyfile.json

            docker build -t gcr.io/coastal-run-106202/keystone-plate:$CIRCLE_BRANCH-$PKG_VER .
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            docker push gcr.io/coastal-run-106202/keystone-plate:$CIRCLE_BRANCH-$PKG_VER

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - staging
                - release
      - push:
          requires:
            - build
          filters:
            branches:
              only:
                - staging
                - release
